In [3]:
import pandas as pd
import numpy as py

precovid_ohio = "precovid_ohio2019.csv"
precovid_ohio_df = pd.read_csv(precovid_ohio)
precovid_ohio_df

,business_id,name,state_,city,stars,review_count,is_open,categories,customer_stars,date_
0,KPZHg7BGkyhLAZmUTIJnMw,& Juice Co.,OH,Columbus,4.5,16,0,"Juice Bars & Smoothies, Vegan, Food, Restauran...",5,1/20/2019 17:28
1,KPZHg7BGkyhLAZmUTIJnMw,& Juice Co.,OH,Columbus,4.5,16,0,"Juice Bars & Smoothies, Vegan, Food, Restauran...",5,2/17/2019 2:45
2,KPZHg7BGkyhLAZmUTIJnMw,& Juice Co.,OH,Columbus,4.5,16,0,"Juice Bars & Smoothies, Vegan, Food, Restauran...",5,8/7/2019 19:15
3,KPZHg7BGkyhLAZmUTIJnMw,& Juice Co.,OH,Columbus,4.5,16,0,"Juice Bars & Smoothies, Vegan, Food, Restauran...",4,3/3/2019 20:32
4,KPZHg7BGkyhLAZmUTIJnMw,& Juice Co.,OH,Columbus,4.5,16,0,"Juice Bars & Smoothies, Vegan, Food, Restauran...",4,5/24/2019 13:33
...,...,...,...,...,...,...,...,...,...,...
5348,FyGavoQ1DdC3ZsjKAfxezA,Zoup!,OH,Columbus,4.0,30,1,"Soup, Salad, Sandwiches, Restaurants",4,3/7/2019 18:25
5349,FyGavoQ1DdC3ZsjKAfxezA,Zoup!,OH,Columbus,4.0,30,1,"Soup, Salad, Sandwiches, Restaurants",4,2/9/2019 21:57
5350,FyGavoQ1DdC3ZsjKAfxezA,Zoup!,OH,Columbus,4.0,30,1,"Soup, Salad, Sandwiches, Restaurants",4,2/2/2019 14:18
5351,IJVqt4PE0QKaqJ2VfBYBZg,Zoup!,OH,Columbus,3.0,19,1,"Sandwiches, Soup, Salad, Restaurants",5,4/16/2019 11:26
5352,IJVqt4PE0QKaqJ2VfBYBZg,Zoup!,OH,Columbus,3.0,19,1,"Sandwiches, Soup, Salad, Restaurants",5,7/3/2019 13:14

In [4]:
postcovid_ohio = "postcovid_ohio2020.csv"
postcovid_ohio_df = pd.read_csv(postcovid_ohio)
postcovid_ohio_df

,business_id,name,state_,city,stars,review_count,is_open,categories,customer_stars,date_
0,JqSL9fNnkwsxQkqGJyHJ2g,101 Beer Kitchen,OH,Westerville,4.5,318,1,"Gastropubs, Breakfast & Brunch, American (New)...",4,5/2/2020 21:57
1,JqSL9fNnkwsxQkqGJyHJ2g,101 Beer Kitchen,OH,Westerville,4.5,318,1,"Gastropubs, Breakfast & Brunch, American (New)...",4,8/2/2020 0:14
2,JqSL9fNnkwsxQkqGJyHJ2g,101 Beer Kitchen,OH,Westerville,4.5,318,1,"Gastropubs, Breakfast & Brunch, American (New)...",5,8/23/2020 17:40
3,JqSL9fNnkwsxQkqGJyHJ2g,101 Beer Kitchen,OH,Westerville,4.5,318,1,"Gastropubs, Breakfast & Brunch, American (New)...",4,5/12/2020 18:38
4,JqSL9fNnkwsxQkqGJyHJ2g,101 Beer Kitchen,OH,Westerville,4.5,318,1,"Gastropubs, Breakfast & Brunch, American (New)...",5,1/26/2020 21:19
...,...,...,...,...,...,...,...,...,...,...
19928,wdkK-cgkYHvS8tp12uwjBQ,Zuko's Pizza,OH,Hilliard,4.0,52,1,"Sandwiches, Pizza, Chicken Wings, Restaurants",5,12/12/2020 1:33
19929,wdkK-cgkYHvS8tp12uwjBQ,Zuko's Pizza,OH,Hilliard,4.0,52,1,"Sandwiches, Pizza, Chicken Wings, Restaurants",5,3/8/2020 20:03
19930,wdkK-cgkYHvS8tp12uwjBQ,Zuko's Pizza,OH,Hilliard,4.0,52,1,"Sandwiches, Pizza, Chicken Wings, Restaurants",5,11/17/2020 2:24
19931,wdkK-cgkYHvS8tp12uwjBQ,Zuko's Pizza,OH,Hilliard,4.0,52,1,"Sandwiches, Pizza, Chicken Wings, Restaurants",5,12/23/2020 22:11
19932,wdkK-cgkYHvS8tp12uwjBQ,Zuko's Pizza,OH,Hilliard,4.0,52,1,"Sandwiches, Pizza, Chicken Wings, Restaurants",5,2/6/2020 18:44

In [5]:
precovid_texas = "precovid_texas2019.csv"
precovid_texas_df = pd.read_csv(precovid_texas)
precovid_texas_df

,business_id,name,state_,city,stars,review_count,is_open,categories,customer_stars,date_
0,FwO183blfDg8g6sFv-NTsQ,15th Street Cafe,TX,Austin,3.5,9,1,"Restaurants, Hotels & Travel, Event Planning &...",4,7/23/2019 18:54
1,Rba9Ol4jnTiov6_iAuoF5g,1618 Asian Fusion,TX,Austin,5.0,641,1,"Food, Breakfast & Brunch, Thai, Restaurants, D...",5,12/23/2019 0:53
2,Rba9Ol4jnTiov6_iAuoF5g,1618 Asian Fusion,TX,Austin,5.0,641,1,"Food, Breakfast & Brunch, Thai, Restaurants, D...",5,10/27/2019 15:03
3,Rba9Ol4jnTiov6_iAuoF5g,1618 Asian Fusion,TX,Austin,5.0,641,1,"Food, Breakfast & Brunch, Thai, Restaurants, D...",5,10/13/2019 20:54
4,Rba9Ol4jnTiov6_iAuoF5g,1618 Asian Fusion,TX,Austin,5.0,641,1,"Food, Breakfast & Brunch, Thai, Restaurants, D...",5,12/8/2019 4:48
...,...,...,...,...,...,...,...,...,...,...
17079,sXgzgNe7YJO1A_86EKUyCw,ZZA Pizza +Ã‚Â Salad,TX,Bee Cave,4.5,63,1,"Gluten-Free, Pizza, Restaurants, Salad",5,12/30/2019 0:59
17080,sXgzgNe7YJO1A_86EKUyCw,ZZA Pizza +Ã‚Â Salad,TX,Bee Cave,4.5,63,1,"Gluten-Free, Pizza, Restaurants, Salad",5,12/18/2019 23:19
17081,sXgzgNe7YJO1A_86EKUyCw,ZZA Pizza +Ã‚Â Salad,TX,Bee Cave,4.5,63,1,"Gluten-Free, Pizza, Restaurants, Salad",5,12/30/2019 23:53
17082,sXgzgNe7YJO1A_86EKUyCw,ZZA Pizza +Ã‚Â Salad,TX,Bee Cave,4.5,63,1,"Gluten-Free, Pizza, Restaurants, Salad",5,12/28/2019 20:31
17083,sXgzgNe7YJO1A_86EKUyCw,ZZA Pizza +Ã‚Â Salad,TX,Bee Cave,4.5,63,1,"Gluten-Free, Pizza, Restaurants, Salad",5,12/21/2019 17:09

In [7]:
postcovid_texas = "postcovid_texas2020.csv"
postcovid_texas_df = pd.read_csv(postcovid_texas,encoding='latin-1')
postcovid_texas_df

,business_id,name,state_,city,stars,review_count,is_open,categories,customer_stars,date_
0,6uSPLo9R0vxtJxPIhsMSMg,101 By Teahaus,TX,Austin,4.0,256,1,"Bubble Tea, Restaurants, Coffee & Tea, Asian F...",3,7/16/2020 4:36
1,6uSPLo9R0vxtJxPIhsMSMg,101 By Teahaus,TX,Austin,4.0,256,1,"Bubble Tea, Restaurants, Coffee & Tea, Asian F...",3,1/23/2020 16:50
2,6uSPLo9R0vxtJxPIhsMSMg,101 By Teahaus,TX,Austin,4.0,256,1,"Bubble Tea, Restaurants, Coffee & Tea, Asian F...",5,5/12/2020 23:50
3,6uSPLo9R0vxtJxPIhsMSMg,101 By Teahaus,TX,Austin,4.0,256,1,"Bubble Tea, Restaurants, Coffee & Tea, Asian F...",5,5/7/2020 21:34
4,6uSPLo9R0vxtJxPIhsMSMg,101 By Teahaus,TX,Austin,4.0,256,1,"Bubble Tea, Restaurants, Coffee & Tea, Asian F...",5,8/5/2020 21:21
...,...,...,...,...,...,...,...,...,...,...
46575,sXgzgNe7YJO1A_86EKUyCw,ZZA Pizza +?Ã¿Salad,TX,Bee Cave,4.5,63,1,"Gluten-Free, Pizza, Restaurants, Salad",3,8/21/2020 22:58
46576,sXgzgNe7YJO1A_86EKUyCw,ZZA Pizza +?Ã¿Salad,TX,Bee Cave,4.5,63,1,"Gluten-Free, Pizza, Restaurants, Salad",5,5/4/2020 23:38
46577,sXgzgNe7YJO1A_86EKUyCw,ZZA Pizza +?Ã¿Salad,TX,Bee Cave,4.5,63,1,"Gluten-Free, Pizza, Restaurants, Salad",5,7/4/2020 21:37
46578,sXgzgNe7YJO1A_86EKUyCw,ZZA Pizza +?Ã¿Salad,TX,Bee Cave,4.5,63,1,"Gluten-Free, Pizza, Restaurants, Salad",5,1/31/2020 20:38
46579,sXgzgNe7YJO1A_86EKUyCw,ZZA Pizza +?Ã¿Salad,TX,Bee Cave,4.5,63,1,"Gluten-Free, Pizza, Restaurants, Salad",5,12/5/2020 14:27